#!/usr/bin/env node

const fs = require('fs');
const resolve = require('path').resolve;
const package = JSON.parse(fs.readFileSync(resolve(__dirname, './package.json')).toString('utf-8'));

if (process.argv.indexOf('-v') > -1 || process.argv.indexOf('--version') > -1) {
    console.log(package.version);
    process.exit();
}

require('yargs')
    .usage(`Usage: ${package.name} [options] <directory>`)
    .example(`${package.name} /path/to/project`, 'Open the project in the editor on default port')
    .example(`${package.name} -p 8080 /path/to/project`, 'Open the project in the editor on port 8080')
    .demandCommand(1)

    .alias('p', 'port')
    .nargs('p', 1)
    .describe('p', 'Set the editor port number')
    .default('p', 9876)

    .alias('v', 'version')
    .describe('v', 'Show current version')

    .help('h')
    .alias('h', 'help');

require('./server');