#!/usr/bin/env node

const fs = require('fs');
const pm2 = require('pm2');
const resolve = require('path').resolve;
const package = JSON.parse(fs.readFileSync(resolve(__dirname, './package.json')).toString('utf-8'));

if (process.argv.indexOf('-v') > -1 || process.argv.indexOf('--version') > -1) {
    console.log(package.version);
    process.exit();
}

process.env.NODE_ENV = "production";

require('yargs')
    .usage(`Usage: ${package.name} [options] <directory>`)
    .example(`${package.name} /path/to/project`, 'Open the project in the editor on default port')
    .example(`${package.name} -p 8080 /path/to/project`, 'Open the project in the editor on port 8080')
    .example(`${package.name} --ssl path/to/keys /path/to/project`, 'Open the project with SSL in the editor on default port')
    .demandCommand(1)
    
    .help('h')
    .alias('h', 'help')

    .alias('p', 'port')
    .nargs('p', 1)
    .describe('p', 'Set the editor port number')
    .default('p', 9876)

    .options({
        headless: { default: false, type: 'boolean' },
        ssl: { type: 'string' },
    })
    .describe('headless', 'Prevent local browser from open')
    .describe('ssl', 'Configures SSL encrpytion. Provide the keys.')

    .alias('v', 'version')
    .describe('v', 'Show current version');

pm2.connect((err) => {
  if (err) {
    console.error(err);
    process.exit(2);
  }
  
  pm2.start(
    'server/index.js',
    { autorestart: false },
    (err, apps) => pm2.disconnect()
  );
});